"""Scaffold files for the ``ddqn-router init`` subcommand."""

from __future__ import annotations

from pathlib import Path

CONFIG_YAML = """\
# ddqn-router configuration — generated by `ddqn-router init`

agents:
  - id: 0
    name: "Billing Agent"
    description: "Handles billing, invoices, payments, subscriptions"
  - id: 1
    name: "Technical Agent"
    description: "Handles bugs, errors, API integration issues"
  - id: 2
    name: "Account Agent"
    description: "Handles account settings, passwords, permissions"

labeler:
  model: "gpt-4o-mini"
  base_url: "https://api.openai.com/v1"
  input: "./data/queries.example.txt"
  output: "./data/tasks.jsonl"
  min_agents: 1
  cache: "./cache/label_cache.jsonl"
  fallback_strategy: "keyword"

dataset:
  input: "./data/tasks.jsonl"
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  output_dir: "./data/"

training:
  total_steps: 20000
  max_steps_per_episode: 10
  val_eval_freq: 2000

output_dir: "./artifacts/"
"""

QUERIES_EXAMPLE = """\
I was charged twice for my subscription this month
Please refund my last payment
Cancel my subscription effective immediately
The API returns a 500 error on every request
Webhook integration is broken since yesterday
Reset my password, I forgot it
Change the email on my account
I cannot login and my last invoice looks wrong
Refund the duplicate charge and also unlock my account
API broken and billing showed wrong amount
Bug on the login page, cannot sign in
Full audit please: billing, API, and account
Why did I get billed for a feature I didn't use
New user — how do I set up my first integration
Give me a CSV export of my usage for last month
"""

GITIGNORE = """\
# ddqn-router scaffolded project
artifacts/
cache/
data/*.jsonl
# Keep the example query list
!data/queries.example.txt

__pycache__/
*.py[cod]
.venv/
venv/
.env
"""

PROJECT_README = """\
# My ddqn-router project

Scaffolded with `ddqn-router init`.

## Next steps

```bash
export DDQN_ROUTER_API_KEY=sk-...

ddqn-router label \\
  --config config.yaml \\
  --input data/queries.example.txt \\
  --output data/tasks.jsonl

ddqn-router dataset split --input data/tasks.jsonl
ddqn-router train --config config.yaml
ddqn-router serve --artifacts ./artifacts/
```
"""

SCAFFOLD_FILES: dict[str, str] = {
    "config.yaml": CONFIG_YAML,
    "data/queries.example.txt": QUERIES_EXAMPLE,
    ".gitignore": GITIGNORE,
    "README.md": PROJECT_README,
}


def write_scaffold(target: Path, force: bool = False) -> list[tuple[Path, str]]:
    """Create scaffold files under ``target``. Returns list of (path, action)."""
    target.mkdir(parents=True, exist_ok=True)
    results: list[tuple[Path, str]] = []
    for rel, content in SCAFFOLD_FILES.items():
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and not force:
            results.append((path, "skipped"))
            continue
        path.write_text(content, encoding="utf-8")
        results.append((path, "created"))
    return results
